disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
  - first_where
  - sorted_imports
  - unneeded_parentheses_in_closure_argument

included:
  - Sources
  - Tests
  - UITests

excluded:
  - FamilyApp.xcodeproj
  - .build
  - DerivedData

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
